# Generated by Django 5.1.4 on 2025-03-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorelogapp', '0002_parent_chore_definition_child_play_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'children'},
        ),
    ]
