# Generated by Django 5.1.4 on 2025-03-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorelogapp', '0003_alter_child_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='done_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.AlterField(
            model_name='chore_definition',
            name='defined_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defined_chores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
