# Generated by Django 5.1.4 on 2025-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorelogapp', '0004_alter_play_child_alter_work_done_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
