# Generated by Django 5.1.4 on 2025-06-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorelogapp', '0005_alter_play_date_logged_alter_work_date_logged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['chore']},
        ),
    ]
