# Generated by Django 5.1.4 on 2025-06-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorelogapp', '0006_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={},
        ),
    ]
